services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: ${GITLAB_CONTAINER_NAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        registry_external_url '${GITLAB_REGISTRY_EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
      - "${GITLAB_REGISTRY_PORT}:5050"
    volumes:
      - config:/etc/gitlab
      - data:/var/opt/gitlab
      - logs:/var/log/gitlab
    shm_size: '8gb'
    restart: unless-stopped
    
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: ${GITLAB_RUNNER_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner
    extra_hosts:
      - "${GITLAB_HOST}:host-gateway"

volumes:
  config:
  data:
  logs:
  runner-config:
